### ISSUE TITLE
installing parsac in later versions of Python 

### ISSUE THREAD

**Issue by gb-THU** [BoldingBruggeman/parsac#12]
Hi all,

I am reporting issues when installing parsac in later Python versions (I am using Python 3.9) and hope you find it of help.

Python 3.9:  replace 'numpy. Inf' by 'numby. inf' in line 173 in 'desolver.py' with the path below
 C:\Python3\lib\site-packages\parsac\optimize\desolver.py
Then delete all files in the __pychache__ folder and re-initiate Python/Anaconda.

Hopefully the issue should be fixed.

Best,
Bo

**Comment by bolding** [comment]
Hi Bo

The issue relates to the version of numpy being used:

numpy.Inf in v1.*

vs

numpy.inf in v2

Strange they did not make it backward compatible.

Karsten

**Comment by jornbr** [comment]
This should now be fixed in the latest release, parsac 0.5.8.
